config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, only: [:new, :create, :index, :destroy]

end

app/models/missing_user.rb
class MissingUser
  def name
    'missing user'
  end

  def admin
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  def user
    super || MissingUser.new
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :not_admin
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def not_admin
    redirect_to posts_path, flash: { error: "You are not authorized" }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, flash: { success: 'Post added' }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    if @post.delete
      redirect_to posts_path, flash: { success: 'Post deleted' }
    else
      redirect_to posts_path, flash: { alert: 'Oops' }
    end
  end

  def index
    @posts = Post.all.includes(:user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :user_id)
  end

  def pundit_user
    Post.find(params[:id]).user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PunditSampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= value %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.haml
%h1 All posts
%table
  %tr
    %th Post title
    %th User
    %th User admin?
    %th Action
  -@posts.each do |post|
    %tr
      %td=post.title
      %td=post.user.name
      %td=post.user.admin
      %td=link_to 'Destroy', post_path(post), method: :delete
%hr
=link_to 'Add new_post', new_post_path

app/views/posts/new.html.haml
%h1 Add new post
=form_for @post do |f|
  =f.label :title
  =f.text_field :title
  =f.label :user
  =f.collection_select :user_id, User.all, :id, :name
  =f.button :submit